version: '3.7'

services:
  dockerized-api:
    build: ./
    restart: unless-stopped
    volumes:
      - ./:/app:cached
    ports:
      - $API_PORT:$API_PORT
    environment:
      - MONGO_HOST=bd-api
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - API_PORT=${API_PORT}

  bd-api:
    image: mongo:4.2
    command: mongod --port ${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ./volumes/mongodb:/data/bd-api
